# Generated by Django 4.2.3 on 2023-07-29 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ajaxtest", "0002_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "verbose_name": "تماس با ما",
                "verbose_name_plural": "تماس ها با ما",
            },
        ),
    ]
