# Generated by Django 4.2.2 on 2023-07-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="blog2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان مقاله")),
                ("descripiton", models.TextField(verbose_name="متن مقاله")),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="وضعیت فعال/غیرفعال"
                    ),
                ),
                (
                    "main_img",
                    models.ImageField(
                        upload_to="images/blogimg", verbose_name="تصویر اصلی مقاله"
                    ),
                ),
            ],
        ),
    ]
