# Generated by Django 4.2.2 on 2023-07-19 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog2", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog2",
            old_name="descripiton",
            new_name="descrioption",
        ),
    ]
