# Generated by Django 4.2.3 on 2023-07-07 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("family", models.CharField(max_length=30)),
                ("slug", models.SlugField(max_length=100)),
                ("age", models.IntegerField(default=20)),
                ("id_active", models.BooleanField(default=True)),
                (
                    "register_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("Email", models.EmailField(max_length=30)),
                ("url", models.URLField()),
            ],
        ),
    ]
