# Generated by Django 4.2.2 on 2023-07-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_author_image_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="image_name",
            field=models.CharField(
                blank=True, default="nophoto.png", max_length=200, null=True
            ),
        ),
    ]
