# Generated by Django 4.2.2 on 2023-07-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_author_image_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="slug",
        ),
        migrations.AddField(
            model_name="author",
            name="nickname",
            field=models.SlugField(default="withot nickname", max_length=100),
        ),
        migrations.AlterField(
            model_name="author",
            name="image_name",
            field=models.CharField(default="nophoto.png", max_length=200),
        ),
    ]
