# Generated by Django 4.2.2 on 2023-07-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_author_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="nickname",
            field=models.CharField(
                blank=True, default="without nickname", max_length=100
            ),
        ),
    ]
