# Generated by Django 4.2.2 on 2023-07-08 03:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_author_nickname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="id_active",
            new_name="is_active",
        ),
    ]
