# Generated by Django 4.2.3 on 2023-07-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("famiy", models.CharField(max_length=30)),
                ("eamil", models.EmailField(max_length=30)),
                ("age", models.PositiveIntegerField()),
                ("username", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=60)),
            ],
        ),
    ]
