# Generated by Django 4.2.3 on 2023-07-29 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apiTestApp", "0002_rename_personmodel_person"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="eamil",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="famiy",
            new_name="family",
        ),
    ]
