# Generated by Django 4.2.3 on 2023-07-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apiTestApp", "0003_rename_eamil_person_email_rename_famiy_person_family"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("register_date", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
